kind: Deployment
apiVersion: apps/v1
metadata:
  name: flink-taskmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      component: flink-taskmanager
  template:
    metadata:
      labels:
        component: flink-taskmanager
    spec:
      containers:
        - name: flink-taskmanager
          image: lizhiyong2000/flink:1.5.1
          args: ["taskmanager", "jobmanager.rpc.address=flink-jobmanager-svc.flink.svc.cluster.local", "blob.server.port=50101"]
          ports:
            - containerPort: 6121
            - containerPort: 6122
            - containerPort: 50101
          resources:
            requests:
              cpu: 100m
